/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.dao.DaoFactory;
import model.dao.clientesDAO;
import model.dao.matriculaDAO;
import model.dao.pagamentosDAO;
import model.entities.clientes;
import model.entities.pagamentos;

/**
 *
 * @author Cleiton
 */
public class TelaPrincipál extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipál
     */
    public TelaPrincipál() {
        initComponents();
        
        clientesDAO cDAO = DaoFactory.createClientesDao();   
       matriculaDAO mDAO = DaoFactory.createMatriculaDao();
        pagamentosDAO pDAO = DaoFactory.createPagamentoDao();

         cmbNomeCliente.addItem(null);
       cDAO.findAll().forEach((p) -> {
           cmbNomeCliente.addItem(p.getNome());
        });
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DataVencendo = new javax.swing.JTextField();
        DancaVencendo = new javax.swing.JTextField();
        cmbNomeCliente = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txtSexo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLucroPorDancas = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuTelaPagamentos = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuMatricula = new javax.swing.JMenuItem();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Aluno:");

        txtCPF.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("CPF:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setText("Aniversario:");

        txtIdade.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setText("prox pag a vencer:");

        DataVencendo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        DataVencendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataVencendoActionPerformed(evt);
            }
        });

        DancaVencendo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        DancaVencendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DancaVencendoActionPerformed(evt);
            }
        });

        cmbNomeCliente.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cmbNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNomeClienteActionPerformed(evt);
            }
        });

        jButton1.setText("Procurar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtSexo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jMenu1.setText("Lucros");

        menuLucroPorDancas.setText("Lucros");
        menuLucroPorDancas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLucroPorDancasActionPerformed(evt);
            }
        });
        jMenu1.add(menuLucroPorDancas);

        jMenuItem2.setText("Pagamentos dos alunos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Criando");

        menuTelaPagamentos.setText("pagamentos mensal");
        menuTelaPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTelaPagamentosActionPerformed(evt);
            }
        });
        jMenu2.add(menuTelaPagamentos);

        jMenuItem4.setText("matricula");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Aluno");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem1.setText("professora");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        menuMatricula.setText("dança");
        menuMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMatriculaActionPerformed(evt);
            }
        });
        jMenu2.add(menuMatricula);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbNomeCliente, javax.swing.GroupLayout.Alignment.LEADING, 0, 298, Short.MAX_VALUE)
                            .addComponent(txtSexo, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DancaVencendo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DataVencendo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataVencendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DancaVencendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DataVencendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataVencendoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataVencendoActionPerformed

    private void DancaVencendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DancaVencendoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DancaVencendoActionPerformed

    private void cmbNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNomeClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        clientesDAO cDAO = DaoFactory.createClientesDao();   
       matriculaDAO mDAO = DaoFactory.createMatriculaDao();
        pagamentosDAO pDAO = DaoFactory.createPagamentoDao();
        
        
         cDAO.findAll().forEach((p) -> {
           cmbNomeCliente.addItem(p.getNome());
      
       });
        
        clientes c =  cDAO.findByNome(cmbNomeCliente.getSelectedItem().toString());
        
                System.out.println(c);
                txtCPF.setText(c.getCpf());
                txtSexo.setText(c.getSexo());
                txtIdade.setText(c.getIdade().toString());
                
                
       pDAO.dataProxPag(new clientes(c.getId())).forEach((p) -> {
         System.out.println(p.getDataProxPag().toString()+" Dança: "+p.getDancas().getDescricao());
           
            System.out.println("a");
           
           
           DancaVencendo.setText(p.getDancas().getDescricao());
           DataVencendo.setText(p.getDataProxPag().toString());
        });
       
      
       

         
        

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuTelaPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTelaPagamentosActionPerformed
        ViewCreatePagamento mtp = new ViewCreatePagamento();
        mtp.show();
    }//GEN-LAST:event_menuTelaPagamentosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ViewPagamento vp = new ViewPagamento();
        vp.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuLucroPorDancasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLucroPorDancasActionPerformed
        ViewGanhos vg = new ViewGanhos();
        
        vg.show();
    }//GEN-LAST:event_menuLucroPorDancasActionPerformed

    private void menuMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMatriculaActionPerformed
        ViewDancas vd = new ViewDancas();
        vd.show();
        
    }//GEN-LAST:event_menuMatriculaActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       ViewMatricula vm = new ViewMatricula();
        vm.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ViewCliente vc = new ViewCliente();
        vc.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ViewProfessora vp = new ViewProfessora();
        vp.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipál.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipál.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipál.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipál.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipál().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DancaVencendo;
    private javax.swing.JTextField DataVencendo;
    private javax.swing.JComboBox<String> cmbNomeCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JMenuItem menuLucroPorDancas;
    private javax.swing.JMenuItem menuMatricula;
    private javax.swing.JMenuItem menuTelaPagamentos;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
